### ISSUE TITLE
Using View Filters : Create Legend

### ISSUE THREAD

**Issue by skehg** [ErikFrits/EF-Tools#12]
﻿

********************

Exception occured - Transaction is being Rollbacked!

Traceback (most recent call last): 
 File "C:\Users\kent.watson\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Views.panel\Column2.stack\ViewFilters.pulldown\ViewFiltersLegend.pushbutton\script.py", line 572, in <module> 
 x = CreateFilters() 
 File "C:\Users\kent.watson\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Views.panel\Column2.stack\ViewFilters.pulldown\ViewFiltersLegend.pushbutton\script.py", line 286, in __init__ 
 self.ShowDialog() 
 File "C:\Users\kent.watson\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Views.panel\Column2.stack\ViewFilters.pulldown\ViewFiltersLegend.pushbutton\script.py", line 406, in button_run 
 legend_view = self.create_legend_view(legend_name) 
 File "C:\Users\kent.watson\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Views.panel\Column2.stack\ViewFilters.pulldown\ViewFiltersLegend.pushbutton\script.py", line 312, in create_legend_view 
 new_legend_view_id = random_legend.Duplicate(ViewDuplicateOption.Duplicate) 
Exception: View cannot be duplicated 

********************

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\kent.watson\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Views.panel\Column2.stack\ViewFilters.pulldown\ViewFiltersLegend.pushbutton\script.py", line 573, in <module>
NameError: name 'x' is not defined

Script Executor Traceback:
IronPython.Runtime.UnboundNameException: name 'x' is not defined
 at IronPython.Runtime.Operations.PythonOps.GetVariable(CodeContext context, String name, Boolean isGlobal, Boolean lightThrow)
 at IronPython.Compiler.LookupGlobalInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by ErikFrits** [comment]
Thank you for submitting the bug.
Could you share a little more details, how you got it and what Revit version did you use?

The error message says that it fails when it duplicates one of the legends, which is weird. 
Can you try this tool in a new empty project?

**Comment by skehg** [comment]
Thanks Erik.  It appears to be something in our template.  I'll do some more trouble shooting and get back to you if I can't resolve it.

**Comment by ErikFrits** [comment]
Sounds great!

I would suggest inspecting your legends. 
Maybe there is some kind of hidden legends in your Revit Project, which can not be duplicated for some reason.

If you know a little python or Dynamo you can try to list all available Legends in your current project, and compare with visible legends in the Project Browser.

That's where I would start. Keep me updated.

**Comment by skehg** [comment]
Hi Erik,

I've found the issue although not sure why its causing it to crash
We have a Legend View template.  Deleting that View template and it works
going to an OTB template and creating a legend view template and it works
Transferring the legend view template from our template into the OTB template and it still works.  A bit weird but at least I know what it is and how to fix it.

**Comment by skehg** [comment]
And thanks again for making some terrific free tools.  They are very helpful.

**Comment by ErikFrits** [comment]
Sorry, I keep missing GitHub notifications...

Maybe all Legend ViewTemplates make it go crazy. 
Thanks for letting me know that, I will have a look at it soon.

If they cause the issue I will either ignore or try to write another logic for them.

Thanks again, and I am Glad you enjoy my tools so much!
