### ISSUE TITLE
EF-Tools- Rooms- Rooms to Ceiling bug

### ISSUE THREAD

**Issue by Robbo1234** [ErikFrits/EF-Tools#23]
Hi there

EF-Tools- Rooms- Rooms to Ceiling is missing in Revit 2021.19 and it currently doesn't work in Revit 2022.1.6

Also, it seems to pick up everything when I select a room/s but it works fine with EF-Tools- Rooms- Rooms to Floor.

Rob

![image](https://github.com/user-attachments/assets/230d79bc-d781-43fd-b1e9-de4281bc7ada)

**Comment by ErikFrits** [comment]
Thanks for heads up. 
I will check what's happening, I think I've tested it on Revit 2023. 

It's not showing up in 2021, because there was no access to create Ceilings in Revit 2021.

**Comment by Robbo1234** [comment]
Hi Erik, I tested RoomstoCeilings in Revit 2023.1.4 and I'm getting this error:

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\rob.cross\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Elements.panel\col2.stack\Rooms.pulldown\RoomsToCeilings.pushbutton\script.py", line 109, in <module>
 File "C:\Users\rob.cross\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\lib\Snippets\_selection.py", line 63, in get_selected_rooms
SystemError: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Script Executor Traceback:
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
 at UIDocument.getADocument(UIDocument* )
 at Autodesk.Revit.UI.UIDocument.get_Document()
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Invoke(Object arg0)
 at IronPython.Runtime.Binding.PythonGetMemberBinder.FastPropertyGet`1.GetProperty(CallSite site, TSelfType target, CodeContext context)
 at IronPython.Compiler.Ast.DynamicGetMemberExpression.GetMemberInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by Robbo1234** [comment]
Fyi, it's working now in both Revit 2022 and 2023 after doing a PyRevit Reload. Thanks

![image](https://github.com/user-attachments/assets/532f0400-820a-40bb-9fbe-b1a68ca68f3e)

**Comment by Robbo1234** [comment]
A suggestion: Can the 'Offset from level (cm)' be controlled by the Project Units?

![image](https://github.com/user-attachments/assets/126b8a61-8aef-4fbd-a2b9-de04ea3dbec2)
