### ISSUE TITLE
EF_Tools-Sheets-EF Sheet Generator not working

### ISSUE THREAD

**Issue by houpr** [ErikFrits/EF-Tools#28]
﻿ Revit 2022.1
﻿ pyRevit v4.8.14
﻿ 
﻿ I just installed EF-Tools and tried Sheet Generator tool. Immediately console with error came out.
﻿ 
﻿ Error Message:
﻿ 
Traceback (most recent call last): 
 File "Q:\Kuba\pyKuba\EF-Tools.extension\EF_Tools.tab\Sheets.panel\col1.stack\EF_SheetGenerator.pushbutton\script.py", line 550, in <module> 
 UI = EF_SheetGenerator() 
 File "Q:\Kuba\pyKuba\EF-Tools.extension\EF_Tools.tab\Sheets.panel\col1.stack\EF_SheetGenerator.pushbutton\script.py", line 150, in __init__ 
 self.populate_title_blocks_combo() 
 File "Q:\Kuba\pyKuba\EF-Tools.extension\EF_Tools.tab\Sheets.panel\col1.stack\EF_SheetGenerator.pushbutton\script.py", line 313, in populate_title_blocks_combo 
 combo_item.IsSelected = True 
UnboundLocalError: Local variable 'combo_item' referenced before assignment.

**Comment by JosephCanMan** [comment]
Error Message:
Traceback (most recent call last):
File "C:\Users\jcannon\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Sheets.panel\col1.stack\EF_SheetGenerator.pushbutton\script.py", line 555, in <module>
UI = EF_SheetGenerator()
File "C:\Users\jcannon\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Sheets.panel\col1.stack\EF_SheetGenerator.pushbutton\script.py", line 158, in __init__
self.ShowDialog()
File "C:\Users\jcannon\AppData\Roaming\pyRevit\Extensions\EF-Tools.extension\EF_Tools.tab\Sheets.panel\col1.stack\EF_SheetGenerator.pushbutton\script.py", line 372, in UIe_RequestNavigate
Start(e.Uri.AbsoluteUri)
WindowsError: [Errno 22] An error occurred trying to start process 'https://learnrevitapi.com/ef-tools-cta' with working directory 'C:\Program Files\Autodesk\Revit 2026'. The system cannot find the file specified.

Similar thing happened when I was in the EF-Sheet Generator, but after I clicked on the Ready to Become pyRevit Hacker?
